# Uncomment these two lines if running on a machine that has AppArmor 3.x but
# a kernel version >= v6.2
#
# NOTE: This has security implications! Research unprivileged user namespaces
# before enabling this in secure environments

#kernel.apparmor_restrict_unprivileged_unconfined=0
#kernel.apparmor_restrict_unprivileged_userns=0
